# Generated by Django 2.1.5 on 2019-02-11 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friends_wishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishes',
            name='target',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='wishtarget',
            name='next',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishtarget',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishtarget',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Wishes'),
        ),
    ]
