# Generated by Django 2.1.5 on 2019-02-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190214_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='url_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='url_video',
            field=models.URLField(null=True),
        ),
    ]
