# Generated by Django 2.1.5 on 2019-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190214_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='url_image',
            field=models.URLField(default=True),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='url_video',
            field=models.URLField(default=True),
        ),
    ]
